name: Zomato Clone - CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-security-scan:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Check dependency vulnerabilities
      - name: NPM Audit
        run: npm audit --audit-level=high
        continue-on-error: true

      # 5. Build React application
      - name: Build React application
        run: npm run build

      # 6. Install Trivy
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
        with:
         version: v0.74.0

      # 7. Trivy filesystem scan
      - name: Trivy filesystem scan
        run: |
          trivy fs . \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0
      
      # 8. Build Docker image
      - name: Build Docker image
        run: docker build -t zomato-clone:${{ github.sha }} .

      # 9. Scan Docker image
      - name: Trivy Docker image scan
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0 \
            zomato-clone:${{ github.sha }}